---
title: "Analysis of archival samples"
author: "Ludvig Larsson"
date: "11/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libs, warning=FALSE, message=FALSE}

library(STutility)
library(magrittr)
library(dplyr)
library(ggplot2)
library(magick)
library(gprofiler2)
library(dplyr)

```


## Prep data
***

Here we'll load a high resolution version of the original images (30% of the full image size).

```{r read_input}

samples <- list.files(path = "../data/archivalcancer/", pattern = "filtered_feature", recursive = TRUE, full.names = TRUE)
imgs <- list.files(path = "../data/archivalcancer/", pattern = "hires_image", recursive = TRUE, full.names = TRUE)
spotfiles <- list.files(path = "../data/archivalcancer/", pattern = "tissue_positions", recursive = TRUE, full.names = TRUE)
json <- list.files(path = "../data/archivalcancer/", pattern = "scalefactors", recursive = TRUE, full.names = TRUE)

infoTable <- data.frame(samples, imgs, spotfiles, json, 
                        age = c("37y", "18y", "10y", "5y"),
                        sample_id = paste0("V10F24-111_", c("A", "B", "C", "D"), "1"),
                        stringsAsFactors = FALSE)

se <- InputFromTable(infoTable)

```

## Quality control
***

The average number of unique genes per spot is around 1k but overall the data is very sparse.

```{r qc}

QC <- function(object) {
  smpls <- GetStaffli(object)@meta.data$sample
  unique.smpls <- unique(smpls)
  df <- do.call(rbind, lapply(unique.smpls, function(s) {
    m <- object@assays$RNA@counts[, smpls == s]
    m <- data.frame(nGene = colSums(m > 0), nUMI = colSums(m), sample = s, stringsAsFactors = FALSE)
  }))
  df %>% group_by(sample) %>%
    summarize(mean_nGene = mean(nGene), median_nGene = median(nGene), max_nGene = max(nGene), min_nGene = min(nGene), 
              mean_nUMI = mean(nUMI), median_nUMI = median(nUMI), max_nUMI = max(nUMI), min_nUMI = min(nUMI))
}

qc.df <- QC(se)
qc.df

```

```{r}

se$age <- factor(se$age, levels = c("37y", "18y", "10y", "5y"))
jpeg(filename = "~/FFPE/201026_cancer_human_archival/plots/violin_plot_qc.jpeg", width = 2000, height = 1000, res = 150)
print(VlnPlot(se, features = c("nFeature_RNA", "nCount_RNA"), group.by = "age", pt.size = 0.5))
dev.off()

mt.genes <- grep(pattern = "^MT-", x = rownames(se), value = T)
ribo.genes <- grep(pattern = "^RPL|^RPS", x = rownames(se), value = T)
se$percent.mito <- Matrix::colSums(se@assays$RNA@counts[mt.genes, ])/se$nFeature_RNA
se$percent.ribo <- Matrix::colSums(se@assays$RNA@counts[ribo.genes, ])/se$nFeature_RNA
jpeg(filename = "~/FFPE/201026_cancer_human_archival/plots/violin_plot_mito_ribo_content.jpeg", width = 2000, height = 1000, res = 150)
print(VlnPlot(se, features = c("percent.mito", "percent.ribo"), group.by = "age", pt.size = 0.5) & scale_y_continuous(labels = scales::percent))
dev.off()

```

## Filter
***

Remove mitochondrial protein coding genes and enrich for protein coding genes


```{r filter, fig.width=14, fig.height=6}

# Remove mitochondrial genes
ensids <- read.table(file = "../data/annotation/GRCh38_genes.tsv", header = T, sep = "\t", stringsAsFactors = FALSE)
bio.keep <- c("protein_coding", "TR_V_gene", "TR_D_gene", "TR_J_gene", "TR_C_gene", "IG_LV_gene", "IG_V_gene", "IG_J_gene", "IG_C_gene", "IG_D_gene")
ensids <- subset(ensids, gene_biotype %in% bio.keep)
mt.genes <- grep(pattern = "^MT-", x = rownames(se), value = TRUE)

keep.genes <- setdiff(ensids$gene_name, mt.genes)
se <- se[intersect(rownames(se), keep.genes), ]

```

## Normalize
***

```{r read_data, include=FALSE}
se <- readRDS("../R_objects/se")
```
```{r normalize, eval=FALSE}

se.split <- lapply(paste0("V10F24-111_", c("A", "B", "C", "D"), "1"), function(i) {
  se <- SubsetSTData(se, expression = sample_id %in% i)
  SCTransform(se, return.only.var.genes = FALSE)
})

```

## Load images
***

```{r load_images, eval=FALSE}

se.split <- lapply(se.split, function(se) {
  LoadImages(se, time.resolve = FALSE, xdim = 2e3)
})

```


## Run analysis
***

```{r analysis, eval=FALSE}

se.split <- lapply(se.split, function(se) {
  se <- se %>%
    RunPCA() %>%
    FindNeighbors(dims = 1:30, reduction = "pca") %>%
    FindClusters() %>%
    RunUMAP(dims = 1:30, reduction = "pca")
})

```

DE analysis

```{r de}

de.markers <- FindAllMarkers(se.split[[4]])

top10 <- de.markers %>% 
  filter(p_val_adj < 0.01, avg_logFC > 0) %>%
  group_by(cluster) %>%
  top_n(n = 10, wt = -p_val_adj)
  
```


```{r}

se <- LoadImages(se, time.resolve = F, xdim = 2e3)
jpeg(filename = "~/FFPE/201026_cancer_human_archival/plots/example_markers.jpeg", width = 4400, height = 4000, res = 300)
FeatureOverlay(se.split[[4]], features = c("OGN", "C3", "PENK", "SERPINA1"), sample.label = F, ncols.features = 2,
               cols = c("darkblue", "cyan", "yellow", "red", "darkred"), add.alpha = T,
               custom.theme = theme(legend.position = "top", plot.margin = margin(0, 0, 0, 0, "cm"))) %>% print()
dev.off()

jpeg(filename = "~/FFPE/201026_cancer_human_archival/plots/clusters.jpeg", width = 2200, height = 2000, res = 300)
FeatureOverlay(se.split[[4]], features = "seurat_clusters", sample.label = F, pt.size = 1.5,
               custom.theme = theme(legend.position = "top", plot.margin = margin(0, 0, 0, 0, "cm"))) %>% print()
dev.off()

jpeg(filename = "~/FFPE/201026_cancer_human_archival/plots/heatmap.jpeg", width = 2200, height = 2000, res = 300)
DoHeatmap(se.split[[4]], features = top10$gene) %>% print()
dev.off()

jpeg(filename = "~/FFPE/201026_cancer_human_archival/plots/UMAP.jpeg", width = 2200, height = 2000, res = 300)
DimPlot(se.split[[4]], label = T, label.size = 10) %>% print()
dev.off()

```

## Date
***

```{r date}
date()
```

## Session info
***

```{r session}
sessionInfo()

```
