---
title: "Organoids"
author: "Ludvig Larsson"
date: "8/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(STutility)
library(magrittr)
library(dplyr)
library(Seurat)
```

```{r load_data}
samples <- list.files("../data/kidneyorganoid", pattern = "raw_feature", recursive = T, full.names = T)
imgs <- list.files("../data/kidneyorganoid", pattern = "small", recursive = T, full.names = T)
spotfiles <- list.files("../data/kidneyorganoid", pattern = "tissue_positions_list", recursive = T, full.names = T)

infoTable <- data.frame(samples, imgs, spotfiles, 
                        sample_id = paste0("sample_", 1:3), 
                        stringsAsFactors = F)

se <- InputFromTable(infoTable, scaleVisium = 0.3, min.spot.feature.count = 500, min.gene.spots = 10)

```

```{r filter_genes}

ensids <- read.table(file = "~/Eduardo/misc/GRCh38_genes.tsv", header = T, stringsAsFactors = F)
rownames(ensids) <- ensids$gene_name
keep.biotypes <- subset(ensids, gene_biotype %in% "protein_coding")$gene_name

# Protein coding genes to remove
rm.genes <- grep(pattern = "^RPL|^RPS|^MT-", x = rownames(se), value = T)

# Determine genes to keep
keep.genes <- setdiff(intersect(rownames(se), keep.biotypes), rm.genes)

# Filter data
se.filtered <- se[keep.genes, ]

```

## Find isolated islets

```{r}

se.filtered <- LoadImages(se.filtered, time.resolve = FALSE)

```

```{r selection, eval=FALSE}

se.filtered <- ManualAnnotation(se.filtered)
se.filtered$organoid <- se.filtered$labels

```

## Crop data

```{r crop}

library(magick)
# Subset data
se.subset.filtered <- SubsetSTData(se.filtered, spots = rownames(subset(se.filtered[[]], organoid %in% paste0("Org", c(1, 3:10)))))

# Get crop windows
pxs <- cbind(GetStaffli(se.subset.filtered)@meta.data[, c("pixel_x", "pixel_y", "sample")], selection = se.subset.filtered$organoid)
pxs.split <- split(pxs, pxs$sample)
orgs <- c()
pxs.split <- setNames(lapply(pxs.split, function(pxs) {
  sel.split <- lapply(split(pxs, pxs$selection), function(pxs) {
    orgs <<- c(orgs, unique(pxs$selection))
    m <- apply(pxs[, 1:2], 2, range)
    centroid <- apply(m , 2, mean)
    widths <- apply(m, 2, function(x) round(diff(range(x)))) + 400
    offsets <- centroid - max(widths)/2
    geometry <- geometry_area(width = max(widths), height = max(widths), x_off = max(offsets[1], 0), y_off = max(offsets[2], 0))
  })
}), nm = unique(pxs$sample))

# Collect crop areas
crop.windows <- do.call(c, lapply(unique(pxs$sample), function(s) {
  crop_geometries <- setNames(pxs.split[[s]], nm = rep(s, length(pxs.split[[s]])))
}))

# Crop data
organoids <- paste0("Org", c(1, 3:10))
se.cropped.list <- lapply(organoids, function(org) {
  crp <- crop.windows[orgs == org]
  se <- CropImages(se.subset.filtered, crop.geometry.list = crp, time.resolve = TRUE, verbose = TRUE)
  return(se)
})

# Filter out spots that are not matching organoid id
se.cropped.list <- lapply(seq_along(se.cropped.list), function(i) {
  SubsetSTData(se.cropped.list[[i]], expression = organoid %in% organoids[i])
})
merged.data <- MergeSTData(x = se.cropped.list[[1]], y = se.cropped.list[2:length(se.cropped.list)])

saveRDS(merged.data, "../R_objects/kidney.organoids.se")
```

```{r load_merged_data}
merged.data <- readRDS("../R_objects/kidney.organoids.se")
merged.data@assays$RNA@counts <- merged.data@assays$RNA@data
```

Subset organoids

```{r subset}

subset.merged.data <- SubsetSTData(merged.data, expression = organoid %in% paste0("Org", c(1:4, 8:10)))

```

Analysis

```{r analysis}

subset.merged.data <- subset.merged.data %>% 
  SCTransform() %>%
  RunPCA() %>%
  RunUMAP(dims = 1:20) %>%
  FindNeighbors(reduction = "pca", dims = 1:20) %>%
  FindClusters()

subset.merged.data <- subset.merged.data %>% 
  FindClusters(resolution = 0.3)

```

```{r, fig.width=6.8, fig.height=10}

s <- data.frame(organoid = subset.merged.data$organoid, sample = GetStaffli(subset.merged.data)@meta.data$sample)
#s <- subset(s, organoid %in% paste0("Org", c(1:4, 8:10)))
s <- s[!duplicated(s), ] %>%
  arrange(factor(organoid, levels = paste0("Org", c(1:4, 8:10))))

pdf(file = "../figures/suppl_figure_XXXX/HE_organoids_kidney.pdf", width = 4, height = 8)
#ImagePlot(se.cropped, indices = s$sample, method = "raster", ncols = 4, annotate = F)
p.list <- lapply(as.integer(s$sample), function(i) {
  FeatureOverlay(subset.merged.data, features = "seurat_clusters", 
               sampleids = i,
               pt.size = 3,
               sample.label = F, show.sb = F,
               ncols.samples = 1,
               custom.theme = theme(
                 legend.position = "none", 
                 plot.margin = margin(0.1,0.1,0.1,0.1, "cm"),
                 plot.title = element_blank()
               )) 
})
cowplot::plot_grid(plotlist = p.list, ncol = 3)
dev.off()

#subset.merged.data <- SubsetSTData(merged.data, expression = organoid %in% paste0("Org", c(1:4, 8:10)))
#subset.merged.data$organoid <- factor(subset.merged.data$organoid, levels = paste0("Org", c(1:4, 8:10)))
#p <- VlnPlot(subset.merged.data, features = "nFeature_RNA", group.by = "organoid")
#ggsave(plot = p, filename = "../figures/suppl_figure_XXXX/vlnplot_kidney.pdf", width = 14, height = 4)

```

# Count QC metrics per organoid

```{r qc_per_organoid}

sapply(paste0("Org", c(1, 3:4, 8:10)), function(org) {
  mean(subset(subset.merged.data[[]], organoid %in% org)$nFeature_RNA)
})

```

```{r, fig.width=8, fig.height=8}

subset.merged.data$organoid <- factor(subset.merged.data$organoid, levels = paste0("Org", c(1:4, 8:10)))
p <- DimPlot(subset.merged.data, group.by = "organoid", cols = c("#332288", "#88CCEE", "#117733", "#DDCC77", "#CC6677","#AA4499"), pt.size = 1.3)
ggsave(plot = p, filename = "../figures/suppl_figure_XXXX/UMAP_kidney.pdf", width = 5, height = 4)

p <- DimPlot(subset.merged.data, group.by = "seurat_clusters", pt.size = 1.3)
ggsave(plot = p, filename = "../figures/suppl_figure_XXXX/UMAP_clusters_kidney.pdf", width = 5, height = 4)

```

```{r, fig.width=8, fig.height=8}

de.markers <- FindAllMarkers(subset.merged.data)
top10 <- de.markers %>%
  group_by(cluster) %>%
  filter(avg_logFC > 0) %>%
  top_n(wt = -p_val_adj, n = 10)
p <- DoHeatmap(subset.merged.data, features = top10$gene)
ggsave(plot = p, filename = "../figures/suppl_figure_XXXX/DE_heatmap_kidney.pdf", width = 7, height = 6)

```

```{r plot_data, fig.height=12, fig.width=12}

FeatureOverlay(se.cropped, features = "nFeature_RNA", sampleids = 1:22, ncols.samples = 5, show.sb = FALSE)

```

QC features

```{r}

se.cropped <- SetIdent(se.cropped, value = "organoid")
VlnPlot(se.cropped, features = "nFeature_RNA")

```

### Run analysis

```{r analysis}

se.cropped <- se.cropped %>% 
  SCTransform() %>%
  RunPCA() %>%
  RunUMAP(dims = 1:20) %>%
  FindNeighbors(reduction = "pca", dims = 1:20) %>%
  FindClusters()

```


```{r, fig.width=12, fig.height=12}

p1 <- DimPlot(se.cropped, group.by = "organoid")
p2 <- DimPlot(se.cropped, group.by = "seurat_clusters")
p3 <- FeaturePlot(se.cropped, features = "nFeature_RNA")
p4 <- FeaturePlot(se.cropped, features = "nCount_RNA")
cowplot::plot_grid(p1, p2, p3, p4)

```

```{r org1, fig.width=8, fig.height=6}

organoids <- paste0("Org", 1:6)
se.list <- lapply(organoids, function(org) {
  se.Org <- SubsetSTData(se.cropped, expression = organoid %in% org)
  se.Org <- se.Org %>%
    SCTransform(return.only.var.genes = FALSE) %>%
    RunPCA() %>%
    RunNMF()
  return(se.Org)
})

# Clustering
se.list <- lapply(seq_along(se.list), function(i) {
  se.Org <- se.list[[i]]
  se.Org <- se.Org %>%
    RunUMAP(dims = 1:20, reduction = "NMF") %>%
    FindNeighbors(dims = 1:20, reduction = "NMF") %>%
    FindClusters(resolution = 0.6)
  return(se.Org)
})

DimPlot(se.list[[3]])

FeatureOverlay(se.list[[4]], features = "seurat_clusters", sampleids = 1:4, ncols.samples = 2, show.sb = F, pt.size = 3)

```

```{r de, fig.width=18, fig.height=4}
i <- 1
de.markers <- FindAllMarkers(se.list[[i]])

top10 <- de.markers %>% 
  group_by(cluster) %>%
  filter(avg_logFC > 0) %>%
  top_n(n = 10, wt = p_val_adj)

jpeg(filename = "~/FFPE/organoids_200820/plots/DE_heatmap.jpeg", width = 2000, height = 2000, res = 150)
DoHeatmap(se.list[[i]], features = top10$gene) %>% print()
dev.off()

#DotPlot(object = se.list[[i]], features = top10$gene) +
#  theme(axis.text.x = element_text(angle = 60, vjust = 0.5)) +
#  scale_color_gradientn(colours = rev(RColorBrewer::brewer.pal(n = 11, name = "RdBu")))

```

Pathway analysis

```{r pathways, fig.width=10, fig.height=5}

pathways <- de.markers %>%
  filter(avg_logFC > 0, p_val_adj < 0.01) %>%
  split(.$cluster) %>%
  lapply(function(set) {
    gost(query = set$gene, sources = "GO:BP", organism = "hsapiens")$result %>%
      top_n(n = 10, wt = -p_value)
  })
pathways <- do.call(rbind, lapply(seq_along(pathways), function(i) {
  pathway <- pathways[[i]]
  pathway$cluster <- i - 1
  return(pathway)
}))

# Plot pathways
pathways$GeneRatio <- pathways$intersection_size/pathways$query_size
p <- ggplot() +
  geom_point(data = pathways, aes(reorder(term_name, -log10(p_value)), -log10(p_value), fill = -log10(p_value), size = GeneRatio), shape = 21) +
  coord_flip() +
  theme_minimal() +
  scale_fill_gradientn(colours = RColorBrewer::brewer.pal(n = 9, name = "Reds")) +
  labs(x = "term") +
  facet_wrap(~cluster, ncol = 1, scales = "free_y")
ggsave(p, filename = "~/FFPE/organoids_200820/plots/pathway_analysis.pdf", width = 10, height = 10)

```
