---
title: "mouse brain multiple sections"
author: "Ludvig Larsson"
date: "12/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries

NOTE: Make sure that you have sctransform v0.2.1 installed to reproduce the plots. Later version might change the normalization outcome.

```{r load_libs, warning=FALSE, message=FALSE}

# devtools::install_github("jbergenstrahle/STUtility")
library(STutility)
library(magrittr)
library(dplyr)
library(harmony)

```

# Load data
***

Here we will include 7 FFPE coronal (mouse brain) section datasets for the analysis.

```{r read_input}

samples <- list.files(path = "../data/mousebrain/", pattern = "filtered_feature_bc_matrix.h5", recursive = T, full.names = T)#[2:8]
imgs <- list.files(path = "../data/mousebrain/", pattern = "tissue_hires_image.png", recursive = T, full.names = T)#[2:8]
spotfiles <- list.files(path = "../data/mousebrain/", pattern = "tissue_positions_list.csv", recursive = T, full.names = T)#[2:8]
json <- list.files(path = "../data/mousebrain/", pattern = "scalefactors_json.json", recursive = T, full.names = T)#[2:8]

infoTable <- data.frame(samples, imgs, spotfiles, json, 
                        condition = c("normal", "normal", "normal", "normal", "normal",  "RU", "RU", "normal"),
                        date = c("NA", "200925", "200925", "200925", "200925", "201016", "201016", "200513"), 
                        sample_id = c("public_data_FF", "V10F24-078_A1", "V10F24-078_B1", "V10F24-078_C1", "V10F24-078_D1", "V10F24-110_A1", "V10F24-110_B1", "V19T26-039_A1"), 
                        stringsAsFactors = F)
infoTable <- infoTable[c(8, 1:7), ]

se <- InputFromTable(infoTable)

```

```{r, fig.width=10, fig.height=10}

ensids <- read.table("../data/annotation/mm10_genes.tsv", header = TRUE, stringsAsFactors = FALSE)
rownames(ensids) <- ensids$gene_name

gene_attr <- do.call(cbind, lapply(unique(se$sample_id), function(i) {
  count = Matrix::rowSums(se@assays$RNA@counts[, se$sample_id %in% i])
}))
colnames(gene_attr) <- unique(se$sample_id)
gene_attr <- data.frame(gene = rownames(se), biotype = ensids[rownames(se), ]$gene_biotype, gene_attr)
gene_attr_melt <- reshape2::melt(gene_attr, measure.vars = colnames(gene_attr)[-c(1, 2)])

# mt-genes
mt.genes <- grep(pattern = "^mt-", x = gene_attr_melt$gene, value = T)
gene_attr_melt$biotype <- ifelse(gene_attr_melt$gene %in% mt.genes, "protein_coding_mitochondrial", gene_attr_melt$biotype)

# ribo-genes
ribo.genes <- grep(pattern = "Rpl|Rps", x = gene_attr_melt$gene, value = T)
gene_attr_melt$biotype <- ifelse(gene_attr_melt$gene %in% ribo.genes, "protein_coding_ribosomal", gene_attr_melt$biotype)

# Add date
conv <- se@meta.data[, c("date", "sample_id")]
conv$sample_id <- gsub("-", ".", conv$sample_id)
conv <- conv[!duplicated(conv), ]
conv <- setNames(conv$date, conv$sample_id)
gene_attr_melt$date <- conv[gene_attr_melt$variable]

gene_attr.summarized <- gene_attr_melt %>% 
  dplyr::group_by(biotype, date, variable) %>%
  dplyr::summarize(count = sum(value)) %>%
  dplyr::group_by(date, variable) %>%
  dplyr::mutate(count = count/sum(count))

gene_attr.summarized$variable <- factor(gene_attr.summarized$variable, levels = c("public_data_FF", "V10F24-078_A1", "V10F24-078_B1", "V10F24-078_C1", "V10F24-078_D1", "V10F24-110_A1", "V10F24-110_B1", "V19T26-039_A1"))
gene_attr.summarized$date <- factor(gene_attr.summarized$date, levels = c("NA", "200925", "201016", "200513"))
p <- ggplot(gene_attr.summarized, aes(x = variable, y = count, fill = biotype)) +
  geom_bar(width = 0.9, stat = "identity", color = "black") +
  theme_classic() +
  labs(y = "RNA biotype content") +
  facet_grid(~date, scales = "free_x", space = "free_x") +
  theme(axis.text.x = element_text(angle = 30, hjust = 1)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = c("#332288", "#6699CC", "#88CCEE", "#44AA99", "#117733", "#999933", "#DDCC77", "#661100", "#CC6677", "#AA4466", "#882255", "#AA4499", "orange"))

png(filename = "~/FFPE/analysis/figures/biotype_composition.png", width = 2000, height = 1000, res = 200)
print(p)
dev.off()

```


## Analysis


```{r normalization}

se <- se %>% SCTransform() %>%
  RunPCA() %>%
  RunUMAP(reduction = "pca", dims = 1:30) %>%
  FindNeighbors(reduction = "pca", dims = 1:30) %>%
  FindClusters()

```

```{r dimplot}

DimPlot(se)

```

## Harmony

```{r harmony, fig.width=10, fig.height=10}

se <- LoadImages(se, time.resolve = FALSE)
se <- WarpImages(se, transforms = list("1" = list(angle = 60), 
                                       "2" = list(shift.x = -50, shift.y = 50), 
                                       "5" = list(angle = -10), 
                                       "6" = list(angle = 20), 
                                       "7" = list(angle = 25)))

library(harmony)
se <- RunHarmony(se, group.by.vars = "date", dims.use = 1:50, assay.use = "SCT")
se <- RunUMAP(se, reduction = "harmony", dims = 1:50, reduction.name = "umap.harmony")
se <- FindNeighbors(se, dims = 1:50, reduction = "harmony")
se <- se  %>% FindClusters(resolution = 0.8)
se <- RunUMAP(se, dims = 1:50, reduction = "harmony", n.components = 3, reduction.name = "umap.3d")

```

```{r rgb}

#se <- ManualAnnotation(se)
#se.subset <- SubsetSTData(se, expression = labels %in% "Default")
#se.subset <- SubsetSTData(se, expression = nFeature_RNA > 100)
p <- ST.DimPlot(se.subset, dims = -c(1:3), reduction = "umap.3d", blend = T, pt.size = 1.2, show.sb = F, ncol = 7, custom.theme = theme(plot.margin = margin(0,0,0,0, "cm"), strip.text = element_blank()))
p

for (i in 1:7) {
  png(file = paste0("../figures/suppl_fig_X/RGBs/RGB_plot_section_", i, ".png"), width = 1000, height = 1000, res = 300)
  p <- ST.DimPlot(se.subset, dims = -c(1:3), reduction = "umap.3d", blend = T, indices = i, pt.size = 1.2, show.sb = F, ncol = 7, custom.theme = theme(plot.margin = margin(0,0,0,0, "cm"), plot.title = element_blank(), strip.text = element_blank()))
  print(p)
  dev.off()
}

```

```{r umap, fig.width=14, fig.height=5}

p <- DimPlot(se, reduction = "umap.harmony", split.by = "date")
p
ggsave(plot = p, filename = "../figures/suppl_fig_X/UMAP_clusters.pdf", width = 15, height = 5)

```

```{r umap, fig.width=14, fig.height=5}

gg <- data.frame(cluster = se$seurat_clusters, experiment = se$date)
gg <- gg %>%
  group_by(experiment, cluster) %>%
  summarize(count = n()) %>%
  group_by(experiment) %>%
  mutate(Freq = count/sum(count))

p <- ggplot(gg) +
  geom_bar(aes(factor(experiment, levels = c("201016", "200925", "200513")), Freq, fill = cluster), stat = "identity", color = "black") +
  coord_flip() +
  scale_y_reverse() +
  theme_minimal()
ggsave(plot = p, filename = "../figures/suppl_fig_X/clusters_distribution.pdf", width = 15, height = 3)

```

```{r qc, fig.width=14, fig.height=10}

gg <- se@meta.data
p1 <- ggplot() +
  geom_violin(data = gg, aes(sample_id, nFeature_RNA, color = sample_id, fill = sample_id), alpha = 0.6) +
  geom_boxplot(data = gg, aes(sample_id, nFeature_RNA, color = sample_id, fill = sample_id), alpha = 1, color = "black", width = 0.3) +
  facet_grid(~date, scales = "free_x", space='free') +
  theme_bw() +
  labs(y = "unique genes", x = "") +
  guides(fill = F, color = F)
p2 <- ggplot() +
  geom_violin(data = gg, aes(sample_id, nCount_RNA, color = sample_id, fill = sample_id), alpha = 0.6) +
  geom_boxplot(data = gg, aes(sample_id, nCount_RNA, color = sample_id, fill = sample_id), alpha = 1, color = "black", width = 0.3) +
  scale_y_continuous(breaks = c(0, 5e3, 10e3, 15e3, 20e3, 25e3)) +
  facet_grid(~date, scales = "free_x", space='free') +
  theme_bw() +
  labs(y = "UMIs", x = "") +
  guides(fill = F, color = F)
p3 <- p1 / p2
ggsave(plot = p3, filename = "../figures/suppl_fig_X/QC_plot.pdf", width = 16, height = 9)

```






