---
title: "all_samples_qc"
author: "Ludvig Larsson"
date: "12/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data

```{r load_libs}
library(STutility)
library(Seurat)
```

Organize all spaceranger output files from FFPE experiments and load them into separate
Seurat objects.

```{r load_libs, eval=FALSE}

# Make sure that only FFPE samples are included
rmvs <- 18:24
samples <- list.files(path = "../data", pattern = "filtered_feature_bc_matrix.h5", recursive = T, full.names = T)[setdiff(1:31, rmvs)]
spotfiles <- list.files(path = "../data", pattern = "tissue_positions_list.csv", recursive = T, full.names = T)[setdiff(1:31, rmvs)]
json <- list.files(path = "../data", pattern = "scalefactors_json.json", recursive = T, full.names = T)[setdiff(1:31, rmvs)]
imgs <- list.files(path = "../data", pattern = "tissue_hires_image.png", recursive = T, full.names = T)[setdiff(1:31, rmvs)]

infoTable <- data.frame(samples, imgs, spotfiles, json, stringsAsFactors = F)
infoTable$date <- c("37 yrs", "18 yrs", "10 yrs", "5 yrs",
                    "6 mos", "6 mos", 
                    "1yr. 8 mos", "1yr. 8 mos", "1yr. 8 mos", "1yr. 8 mos",
                    "1 mo", "1 mo", "1 mo", 
                    "1 mo", "1 mo", "1 mo", "1 mo", 
                    "3 mos", "3 mos", "3 mos", "3 mos",
                    "3 mos", "3 mos",
                    "3 mos")

se.list <- lapply(1:nrow(infoTable), function(i) {
  InputFromTable(infoTable[i, ])
})

```

```{r calc_qc}

sampleids <- do.call(rbind, strsplit(infoTable$samples, "/"))[, 4]
qc.matrix <- do.call(rbind, lapply(seq_along(se.list), function(i) {
  data.frame(unique_genes = se.list[[i]]$nFeature_RNA, 
             UMIs = se.list[[i]]$nCount_RNA, 
             sample = sampleids[i], date = se.list[[i]]$date)
}))

```


```{r plot, fig.width=10, fig.height=6}

lvls <- c("1 mo", "3 mos", "6 mos", "1yr. 8 mos", "5 yrs", "10 yrs", "18 yrs", "37 yrs")
qc.matrix$date <- factor(qc.matrix$date, levels = lvls)
p1 <- ggplot(qc.matrix, aes(sample, unique_genes, fill = date)) +
  geom_violin() +
  geom_boxplot(width = 0.1) +
  facet_grid(~date, scales = "free", space='free') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        axis.title.x = element_blank(),
        panel.background = element_blank(), 
        panel.grid = element_line(colour = "lightgray", linetype = "longdash")) +
  guides(fill = F)
p2 <- ggplot(qc.matrix, aes(sample, UMIs, fill = date)) +
  geom_violin() +
  geom_boxplot(width = 0.1) +
  facet_grid(~date, scales = "free", space='free') +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        axis.title.x = element_blank(),
        panel.background = element_blank(), 
        panel.grid = element_line(colour = "lightgray", linetype = "longdash")) +
  guides(fill = F)
p1 / p2

```

## date 
***

```{r}
date()
```

## Session
***

```{r}
sessionInfo()
```


