---
title: "cell_segmentation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_libs}
library(EBImage)
library(ggplot2)
library(cowplot)
library(magrittr)
library(zeallot)
source("global_functions_segmentation.R")
```


## Segmentation
***

Apply simple segmentation to DAPI stain

```{r segmentation_run, fig.height=3, fig.width=6}

img.files <- "../data/immunofluorescence/DAPI_small.png"

cells <- readImage(img.files, type = "PNG")
cells <- channel(cells, mode = "gray")
cells <- EBImage::normalize(cells)

# tests
nmask = thresh(cells, w=10, h=10, offset=0.05)
nmask = opening(nmask, makeBrush(5, shape='disc'))
nmask = fillHull(nmask)
nmask = bwlabel(nmask)

```

## Count cells
***

```{r count_features, fig.height=4, fig.width=12}
cat("Total number of cells: ", max(nmask), "\n")

par(mfrow = c(1, 2))
display(cells[500:1500, 500:1500], method = "raster")
text(x = 10, y = 20, label = "raw signal", adj = c(0, 1), col = "orange", cex = 1.5)
display(nmask[500:1500, 500:1500], method = "raster")
text(x = 10, y = 20, label = "segmetned nuclei", adj = c(0, 1), col = "orange", cex = 1.5)

```

## Date
***

```{r}
date()
```

## Session
***

```{r}
sessionInfo()
```


